export const InitialAppointData = [
    {
        Sr: 1,
        Name: "Dhairya Patel",
        Schedule: "12:00 PM",
        Action: "Cancelled",
        PaymentStatus: "Pending",
    },
    {
        Sr: 2,
        Name: "Dhairya Patel",
        Schedule: "12:00 PM",
        Action: "Cancelled",
        PaymentStatus: "Paid",
    },
    {
        Sr: 3,
        Name: "Dhairya Patel",
        Schedule: "12:00 PM",
        Action: "Cancelled",
        PaymentStatus: "Paid",
    },
    {
        Sr: 4,
        Name: "Dhairya Patel",
        Schedule: "12:00 PM",
        Action: "Cancelled",
        PaymentStatus: "Pending",
    }, 
    {
        Sr: 5,
        Name: "Dhairya Patel",
        Schedule: "12:00 PM",
        Action: "Cancelled",
        PaymentStatus: "Pending",
    }, 
    {
        Sr: 5,
        Name: "Dhairya Patel",
        Schedule: "12:00 PM",
        Action: "Cancelled",
        PaymentStatus: "Pending",
    }, 
    {
        Sr: 6,
        Name: "Dhairya Patel",
        Schedule: "12:00 PM",
        Action: "Cancelled",
        PaymentStatus: "Pending",
    }, 
    {
        Sr: 7,
        Name: "Dhairya Patel",
        Schedule: "12:00 PM",
        Action: "Cancelled",
        PaymentStatus: "Pending",
    }, 
    {
        Sr: 8,
        Name: "Dhairya Patel",
        Schedule: "12:00 PM",
        Action: "Cancelled",
        PaymentStatus: "Pending",
    }, 
    {
        Sr: 9,
        Name: "Dhairya Patel",
        Schedule: "12:00 PM",
        Action: "Cancelled",
        PaymentStatus: "Pending",
    },
    {
        Sr: 10,
        Name: "Dhairya Patel",
        Schedule: "12:00 PM",
        Action: "Cancelled",
        PaymentStatus: "Pending",
    }
]
